# Generated by Django 3.1 on 2021-10-22 19:49

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank=True, verbose_name=store.models.Variation),
        ),
    ]
